In [3]:
import numpy         #printing the second index in the array
arr=numpy.array([10,23,23,4,5])
print(arr[1])

23


In [6]:
import numpy as np          #creating np as alternate keyword for importing numpy
arr=np.array([23,40,34,45,46])
print(arr)

[23 40 34 45 46]


In [7]:
import numpy as np        #checking numpy version 
print(np.__version__)

1.24.3


In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.linspace(0,19)

array([ 0.        ,  0.3877551 ,  0.7755102 ,  1.16326531,  1.55102041,
        1.93877551,  2.32653061,  2.71428571,  3.10204082,  3.48979592,
        3.87755102,  4.26530612,  4.65306122,  5.04081633,  5.42857143,
        5.81632653,  6.20408163,  6.59183673,  6.97959184,  7.36734694,
        7.75510204,  8.14285714,  8.53061224,  8.91836735,  9.30612245,
        9.69387755, 10.08163265, 10.46938776, 10.85714286, 11.24489796,
       11.63265306, 12.02040816, 12.40816327, 12.79591837, 13.18367347,
       13.57142857, 13.95918367, 14.34693878, 14.73469388, 15.12244898,
       15.51020408, 15.89795918, 16.28571429, 16.67346939, 17.06122449,
       17.44897959, 17.83673469, 18.2244898 , 18.6122449 , 19.        ])

In [11]:
np.linspace(0,19,50)

array([ 0.        ,  0.3877551 ,  0.7755102 ,  1.16326531,  1.55102041,
        1.93877551,  2.32653061,  2.71428571,  3.10204082,  3.48979592,
        3.87755102,  4.26530612,  4.65306122,  5.04081633,  5.42857143,
        5.81632653,  6.20408163,  6.59183673,  6.97959184,  7.36734694,
        7.75510204,  8.14285714,  8.53061224,  8.91836735,  9.30612245,
        9.69387755, 10.08163265, 10.46938776, 10.85714286, 11.24489796,
       11.63265306, 12.02040816, 12.40816327, 12.79591837, 13.18367347,
       13.57142857, 13.95918367, 14.34693878, 14.73469388, 15.12244898,
       15.51020408, 15.89795918, 16.28571429, 16.67346939, 17.06122449,
       17.44897959, 17.83673469, 18.2244898 , 18.6122449 , 19.        ])

In [12]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [15]:
arr=np.random.randint(1,3,100)

In [16]:
arr

array([1, 2, 1, 2, 2, 2, 1, 1, 2, 1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 2, 2, 2,
       1, 1, 1, 1, 2, 1, 1, 2, 2, 1, 1, 2, 1, 2, 1, 1, 1, 1, 2, 2, 1, 2,
       2, 2, 1, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 1, 2, 1, 2, 1, 2, 1, 2, 1,
       1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 2, 2, 1, 2, 2, 1, 1, 2, 1, 2, 2, 1,
       1, 1, 2, 2, 1, 2, 2, 1, 2, 1, 2, 1])

In [17]:
arr=np.random.randint(1,3, size =(3,2))

In [18]:
arr

array([[2, 1],
       [1, 1],
       [2, 1]])

In [19]:
arr=np.arange(25)

In [20]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
arr.argmax()

24

In [23]:
arr=np.random.randint(0,52,10)

In [24]:
arr

array([15, 32, 38, 40,  4, 14,  5, 21, 24, 26])

In [25]:
np.sort(arr)

array([ 4,  5, 14, 15, 21, 24, 26, 32, 38, 40])

In [28]:
arr.dtype

dtype('int32')

In [30]:
arr=np.arange(0,11)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
arr[6]

6

In [33]:
arr[2:5]

array([2, 3, 4])

In [34]:
arr[0:4] =100

In [35]:
arr

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10])

In [36]:
arr[:]=100

In [37]:
arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [38]:
arr=np.array([23,34,65,78,98])

In [40]:
type(arr)

numpy.ndarray

In [41]:
arr.dtype

dtype('int32')

In [44]:
import numpy as np
arr=np.array(4)  #zero dimensional array


In [45]:
arr

array(4)

In [46]:
arr=np.array([1,2,3,4,5,6,6,78])  #1D array

In [47]:
arr

array([ 1,  2,  3,  4,  5,  6,  6, 78])

In [49]:
arr=np.array([[1,2,3],[4,5,6]])  #2D array

In [50]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) # 3D array

In [52]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [56]:
arr0=np.array(4)
arr1=np.array([1,2,3,4,5,6,6,78])
arr2=np.array([[1,2,3],[4,5,6]])
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [59]:
print(arr0)
print(arr1)
print(arr2)
print(arr3)

4
[ 1  2  3  4  5  6  6 78]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [60]:
print(arr0.ndim)     #checking number of dimensions of array using "ndim" moethod
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

0
1
2
3


In [61]:
import numpy as np      
arr=np.array([1,2,3,4,5,6,7], ndmin=5)  #creating an array with 5 dimension using "ndmin" argument

In [62]:
arr

array([[[[[1, 2, 3, 4, 5, 6, 7]]]]])

In [63]:

arr.ndim

5

In [64]:
arr.dtype

dtype('int32')

## Indexing in Array

In [65]:
import numpy as np   #1D array
arr=np.array([1,2,3,4,5])
print(arr[3])

4


In [66]:
arr[2] + arr[4]     #addition using index

8

In [70]:
arr=np.array([[1,2,3],[4,5,6]]) #2D array print 2nd element in the first row.. Here the first row is indexed "0" and the 2nd "1"
print("2nd element on 1st row: ",arr[0,1])

2nd element on 1st row:  2


In [72]:
arr[1,-1]  # accessing the last element of the 2nd row
#arr[1,2] 

6

In [74]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]) #3D array accessing the 3rd element of the 2nd array of first array
print(arr[0,1,2])


6


In [75]:
arr=np.array([[2,4,6],[8,10,12]]) # indexing with negative index
print(arr[0,-1])

6


# Numpy Array Slicing 

In [76]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:4])# start :end

[2 3 4]


In [83]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[::2])  # step gives instruction how the slicing will go,, for exmaple here is in 2s

#":::" meaning start, end and stesp

[1 3 5 7 9]


In [87]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]]) # slicing 2D array
print(arr[1,1:4])  # This means 1 is the index of the 2nd element in the array, while 1:4 means that we are returning elements from index 1 before 4

[7 8 9]


In [95]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2, 1:4])# Here "0:2" means the first and 2nd array which has index 0 and 1. now we are printing element in both arrays from index 1 x to 4. 

[[2 3 4]
 [7 8 9]]


  # Numpy array Shape

In [96]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]]) ## this returns the number of rows and columns in an array
print(arr.shape)


(2, 5)


In [99]:
arr=np.array([1,2,3,4], ndmin=6)
print(arr.shape)

(1, 1, 1, 1, 1, 4)


## Numpy Array Reshaping

In [102]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
narr=arr.reshape(4,3)  #Here we changing the shape of the array from 1D to 2D
print(narr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [105]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2) # This means there are 2 arrays in an array and each array has 3 elemnets  finally each of the 3 elements has 2 element or values
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
