Numpy Exercise

In [1]:
#Exercise 1 import numpy as np
import numpy as np


In [65]:
#Exercise 2  checking the numpy version 
print(np.__version__)

1.24.3


In [2]:
#Exercise 3
arr=np.zeros(10)  # creating zeros with size 10

In [3]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [61]:
 #Exercise 4
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) #Shape and Size 


In [62]:
#arr.size # finding the size of the array.Total number of element in an array
np.size(arr)

12

In [8]:
arr.shape ## finding the shape of an array. This indicates the nunmber elements stored along each dimension of the array 

(2, 2, 3)

In [15]:
arr.ndim ##number of axes, or dimensions, of the array. 

3

In [9]:
#Exercise 5 (Writing a numpy fucntion that helps to return documentation of the add function)
import numpy as np   
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [17]:
#Exercise 6  creating a null vector in numpy
import numpy as np
arr=np.zeros(10)


In [21]:
arr[4]=1    # making the fifth 1

In [22]:
arr

array([0., 0., 0., 0., 1., 1., 0., 0., 0., 0.])

In [25]:
#Exercise 7 
arr=np.arange(10,49)  # creating a vector ranging from 10 to 49 

In [27]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [28]:
#Exercise 8  Reversing a vector (first element becomes last)
brr=np.array([1,2,3,4,5,6,7,8,9])

In [29]:
res=np.flip (brr) #using the 'flip()' method

In [30]:
res

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [33]:
#Exercise 9     Create a 3x3 matrix using a range from 0 to 8
arr=np.arange(0,9)   #creating a range

In [34]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [35]:
arr.reshape(3,3)  #Create a 3x3 matrix, simply by using the "reshape()" method

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [40]:
#Exercise 10 Find indices of non-zero elements from an array  using the where method
arr=np.array([1,2,0,0,4,0])
np.where(arr!=0)  #!=0, means not 0. This will return the indices of numbers other than 0


(array([0, 1, 4], dtype=int64),)

In [55]:
#Exercise 11  Creating a 3x3 identity matrix
orr=np.identity(2)  #first adjust the identity to 2


In [56]:
orr

array([[1., 0.],
       [0., 1.]])

In [57]:
np.dstack([orr]*3)   #stacking the array to 3D 

array([[[1., 1., 1.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [1., 1., 1.]]])

In [82]:
#Exercise 12  Creating a 3x3x3 array with random values
err=np.random.randint(1,7,27) #created a random numbers between 1 and 7 in 27 values 

In [80]:
err

array([1, 6, 2, 5, 2, 4, 6, 4, 2, 3, 6, 4, 5, 4, 5, 3, 4, 3, 6, 5, 4, 6,
       5, 3, 5, 2, 4])

In [81]:
err.reshape(3,3,3) # reshaping the array from 1D to 3x3x3 Dimension

array([[[1, 6, 2],
        [5, 2, 4],
        [6, 4, 2]],

       [[3, 6, 4],
        [5, 4, 5],
        [3, 4, 3]],

       [[6, 5, 4],
        [6, 5, 3],
        [5, 2, 4]]])

In [86]:
# Exercise 13 Create a 10x10 array with random values and find the minimum and maximum values
trr=np. random.randint(45,240,100) #creating a range of random values and its size

In [87]:
trr

array([ 77,  62, 176, 232, 100, 105,  68, 126, 144, 155, 226,  91,  85,
       152,  59, 146, 118, 112,  95, 131, 164, 205, 165, 153, 136, 184,
       126,  79, 164, 117,  56, 169, 218, 228, 211, 113,  95,  78,  79,
       212, 196, 186, 131, 122,  99, 171, 159,  80, 121, 124, 125, 170,
       201, 121, 144, 150, 118, 184, 233,  91, 114, 235, 224,  66, 223,
       234,  97,  89, 235, 150,  65, 158, 228,  49, 112, 156, 191, 204,
       153, 121,  63, 134,  89, 159, 103,  54, 161,  83,  53, 223, 188,
       237, 127, 142, 122, 141, 194, 133, 145, 127])

In [88]:
trr.reshape(10,10) # reshaping it to 10x10

array([[ 77,  62, 176, 232, 100, 105,  68, 126, 144, 155],
       [226,  91,  85, 152,  59, 146, 118, 112,  95, 131],
       [164, 205, 165, 153, 136, 184, 126,  79, 164, 117],
       [ 56, 169, 218, 228, 211, 113,  95,  78,  79, 212],
       [196, 186, 131, 122,  99, 171, 159,  80, 121, 124],
       [125, 170, 201, 121, 144, 150, 118, 184, 233,  91],
       [114, 235, 224,  66, 223, 234,  97,  89, 235, 150],
       [ 65, 158, 228,  49, 112, 156, 191, 204, 153, 121],
       [ 63, 134,  89, 159, 103,  54, 161,  83,  53, 223],
       [188, 237, 127, 142, 122, 141, 194, 133, 145, 127]])

In [93]:
trr.min() # finding the min of the array
#np.min(trr)

49

In [94]:
trr.max()  # finding the max of the array
#np.max(trr)

237

In [99]:
#Exercise 14  Create a random vector of size 30 and find the mean value
arr=np.random.randint(4,400,30) #creating a range of random values and setting its size to 30 

In [100]:
arr

array([ 99, 219, 147,  19, 103, 350,  70,  47, 127, 396,  71, 315, 183,
       209, 103, 323, 267, 216, 178, 134, 165, 156,  45, 242, 212,  58,
       248,  56,  14, 280])

In [101]:
np.mean(arr)

168.4

In [116]:
#Exercise 15  Create a 2d array with 1 on the border and 0 inside
rrr=np.ones((4,4))  #creating 2D array with 1


In [117]:
rrr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [118]:
#constructing a border with 0s inside and array outside
#slicing through the rows and columns such that outer border is not included
rrr[1:3,1:3]=0  

In [119]:
rrr

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [142]:
import numpy as np 
arr=np.ones((5,5)) #creating 5x5 array

#arr=np.pad(arr, pad_width=1, mode='constant', constant_values=0)
arr[:,[0,-1]]=0
arr[[0,-1],:]=0

In [143]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])